scopes:
  source:
    files:
      critical:
        include:
          - "**"

merge_protections_settings:
  reporting_method: check-runs
  post_comment: true
  auto_merge_conditions: true

merge_protections:
  - name: VM2 whitespace filename scope protected merge
    if:
      - base = main
      - scope = critical
    success_conditions:
      - check-success = vm2-whitespace-ci
